services:
  - type: web
    name: selfcast-website-builder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
